[![Deploy Sovereign OS](https://github.com/godriches36/BlackSunGod/actions/workflows/static.yml/badge.svg?branch=main&event=page_build)](https://github.com/godriches36/BlackSunGod/actions/workflows/static.yml)
